version: '3'
services:

  account:
    depends_on:
      - account-database
    image: eccom/account
    build: account
    entrypoint: npm run start-dev
    volumes:
      - ./account:/app
    ports:
      - 3000:3000
    
  account-database:
    image: mongo
    container_name: account-database   
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin 
      - MONGO_INITDB_DATABASE=accounts
    ports:
      - 27017:27017

  product:
    depends_on:
      - product-database
    image: eccom/product
    build: product
    entrypoint: npm run start-dev
    volumes:
      - ./product:/app
    ports:
      - 3001:3000

  product-database:
    image: mysql
    container_name: product-database
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=products
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      
    ports: 
      - 3307:3306