version: '3.9'
services:
  product:
    image: eccom/product
    build: product

  account:
    image: eccom/account
    build: account
    




#rodar no terminal para subir docker-compose up
#rodar no terminal para parar docker-compose down